import type { TextUIPart, UIMessage } from "ai";

export const AutoMemoryIndexName = "MEMORY.md";

// Header doubles as the marker for identifying auto-memory reminders.
const AutoMemoryHeader = "# Long-term Memory Index (MEMORY.md)";

export function isAutoMemorySystemReminder(content: string): boolean {
  return content.includes(AutoMemoryHeader);
}
export const AutoMemoryLockName = ".consolidate-lock";
/**
 * Sidecar metadata file that maps an obfuscated project directory
 * (`~/.pochi/projects/<repoKey>/`) back to its source repository. Lets users
 * — and future tooling — identify which project a hashed directory belongs
 * to without scanning every memory or transcript file.
 */
export const AutoMemoryProjectInfoName = "project.json";
export const AutoMemoryMaxIndexLines = 200;
export const AutoMemoryMaxIndexBytes = 25_000;
export const AutoMemoryMaxManifestEntries = 200;

export const AutoMemoryTypeValues = [
  "user",
  "feedback",
  "project",
  "reference",
] as const;

export type AutoMemoryType = (typeof AutoMemoryTypeValues)[number];

export type AutoMemoryManifestEntry = {
  filename: string;
  name?: string;
  description?: string;
  type?: AutoMemoryType;
  updatedAt?: number;
};

export type AutoMemoryContext = {
  enabled: true;
  repoKey: string;
  memoryDir: string;
  indexPath: string;
  indexContent: string;
  indexTruncated: boolean;
  manifest: AutoMemoryManifestEntry[];
  /**
   * Directory holding per-task transcript markdown files for this repo,
   * e.g. `~/.pochi/projects/<repoKey>/transcripts`. The dream agent is
   * granted read-only file-tool access to this directory and reads
   * transcripts on demand instead of receiving them inline in the prompt.
   */
  transcriptDir: string;
};

type TruncateResult = {
  content: string;
  truncated: boolean;
};

const TruncationNotice =
  "\n\n[Long-term memory index truncated: open MEMORY.md directly if more entries are needed.]";

export function truncateAutoMemoryIndex(content: string): TruncateResult {
  const normalized = content.trimEnd();
  let truncated = false;
  let result = normalized;

  const lines = result.split(/\r?\n/);
  if (lines.length > AutoMemoryMaxIndexLines) {
    result = lines.slice(0, AutoMemoryMaxIndexLines).join("\n");
    truncated = true;
  }

  const encoder = new TextEncoder();
  while (
    encoder.encode(result + TruncationNotice).byteLength >
    AutoMemoryMaxIndexBytes
  ) {
    const next = result.slice(0, Math.max(0, result.length - 512)).trimEnd();
    if (next.length === result.length) break;
    result = next;
    truncated = true;
  }

  return {
    content: truncated ? `${result}${TruncationNotice}` : result,
    truncated,
  };
}

export function formatAutoMemoryManifest(
  manifest: readonly AutoMemoryManifestEntry[],
): string {
  if (manifest.length === 0) return "No topic files yet.";

  const entries = manifest
    .slice(0, AutoMemoryMaxManifestEntries)
    .map((entry) => {
      const type = entry.type ?? "reference";
      const title = entry.name || entry.filename;
      const description = entry.description ? `: ${entry.description}` : "";
      return `- [${type}] ${entry.filename} (${title})${description}`;
    })
    .join("\n");

  if (manifest.length > AutoMemoryMaxManifestEntries) {
    return `${entries}\n\nShowing ${AutoMemoryMaxManifestEntries} of ${manifest.length} topic files. Read MEMORY.md for the complete index.`;
  }
  return entries;
}

const IndexTypeOrder: readonly (AutoMemoryType | "other")[] = [
  ...AutoMemoryTypeValues,
  "other",
];

const GeneratedIndexHeader = `# Memory Index

<!-- Generated by Pochi from the frontmatter of the topic files in this directory.
     Do not edit by hand: this file is rewritten from the topic files and any
     manual change is lost. To change an entry, edit the topic file's
     \`name\` / \`description\` frontmatter instead. -->`;

/**
 * Render MEMORY.md from the topic manifest.
 *
 * The index is a derived artifact: agents never write it, which removes one
 * whole write from every extraction run and makes it impossible for a newly
 * written topic file to stay invisible because the index write never happened.
 */
export function renderAutoMemoryIndex(
  manifest: readonly AutoMemoryManifestEntry[],
): string {
  if (manifest.length === 0) {
    return `${GeneratedIndexHeader}\n\nNo topic files yet.\n`;
  }

  const sections = IndexTypeOrder.map((type) => {
    const entries = manifest
      .filter((entry) => (entry.type ?? "other") === type)
      .slice()
      .sort((a, b) => a.filename.localeCompare(b.filename));
    if (entries.length === 0) return undefined;

    const lines = entries.map((entry) => {
      const title = entry.name || entry.filename;
      const description = entry.description ? `: ${entry.description}` : "";
      return `- ${entry.filename} (${title})${description}`;
    });
    return `## ${type}\n\n${lines.join("\n")}`;
  }).filter((section): section is string => section !== undefined);

  return `${GeneratedIndexHeader}\n\n${sections.join("\n\n")}\n`;
}

/**
 * Static memory guidance for the system prompt — rules + paths, no index.
 * The index is injected separately so the system prefix stays cacheable
 * across sessions. Mirrors claude-code's memdir split.
 */
export function buildAutoMemoryStaticPrompt(
  context: AutoMemoryContext | undefined,
): string {
  if (!context) return "";

  return `====

LONG-TERM MEMORY

Long-term memory is enabled for this workspace. It is stored in local markdown files, shared by all worktrees for this repository.

Memory directory: ${context.memoryDir}
Index file: ${context.indexPath}

Use this memory only for durable information that should carry across future sessions. Do not store one-off task progress, temporary debugging notes, command output, git history, or facts already documented in project rules.

Memory file rules:
- MEMORY.md is a generated index. Never write to it: it is rebuilt automatically from the topic files' frontmatter, and manual edits are overwritten.
- Topic files live directly in the memory directory as markdown files. Do not use subdirectories.
- Every topic file must begin with YAML frontmatter containing name, description, and type. The index shows name and description, so keep them accurate.
- type must be one of: user, feedback, project, reference.
- Prefer updating an existing topic file over creating a duplicate.

A background memory agent automatically reviews completed tasks and updates long-term memory when it finds durable information. Leave proactive memory capture to that agent by default. If you independently identify something worth remembering, do not update memory unless you first ask the user and receive explicit confirmation.

A direct user request to remember or forget something already counts as confirmation. When the user asks you to remember something, write or update the relevant topic file. When the user asks you to forget something, remove or edit the relevant topic file. The index picks the change up on its own. Ask a follow-up only if the memory to remove is ambiguous.

The long-term memory directory is an explicit exception to the normal relative-path tool rule. You may use the absolute paths above when reading or writing memory files.

The current MEMORY.md index is delivered separately as its own system reminder on the first user turn. That snapshot is taken at the start of the task and is intentionally NOT refreshed mid-task — new memories you write here become visible only in the next task session.`;
}

/** MEMORY.md snapshot block, injected via {@link injectAutoMemory}. */
export function buildAutoMemoryDynamicPrompt(
  context: AutoMemoryContext | undefined,
): string {
  if (!context) return "";

  const indexContent = context.indexContent.trim()
    ? context.indexContent
    : "(MEMORY.md is currently empty.)";

  return `${AutoMemoryHeader}
This snapshot of MEMORY.md was captured at the start of the task and will not be refreshed until the next task session. Topic files referenced here live under ${context.memoryDir}.

${indexContent}`;
}

/**
 * Remove any previously-injected auto-memory reminder from user messages.
 * Used when project memory is disabled so the snapshot (which may have been
 * persisted into the first user message on an earlier turn) stops being sent.
 */
function stripAutoMemoryReminders(messages: UIMessage[]): UIMessage[] {
  for (const message of messages) {
    if (message.role !== "user") continue;
    const parts = message.parts ?? [];
    const filtered = parts.filter(
      (part) =>
        part.type !== "text" || !isAutoMemorySystemReminder(part.text ?? ""),
    );
    if (filtered.length !== parts.length) {
      message.parts = filtered;
    }
  }
  return messages;
}

/**
 * Inject the MEMORY.md snapshot as a dedicated system reminder on the first
 * user turn. Idempotent — replaces any prior auto-memory reminder.
 *
 * When memory is disabled (no context), strips any previously-injected
 * reminder instead, so it stops being sent for the current task.
 */
export function injectAutoMemory(
  messages: UIMessage[],
  context: AutoMemoryContext | undefined,
): UIMessage[] {
  const memoryBlock = context ? buildAutoMemoryDynamicPrompt(context) : "";
  if (!memoryBlock) return stripAutoMemoryReminders(messages);
  if (messages.length !== 1) return messages;

  const messageToInject = messages.at(-1);
  if (!messageToInject || messageToInject.role !== "user") return messages;

  const reminderPart: TextUIPart = {
    type: "text",
    text: `<system-reminder>${memoryBlock}</system-reminder>`,
  };

  const filteredParts = (messageToInject.parts ?? []).filter(
    (part) =>
      part.type !== "text" || !isAutoMemorySystemReminder(part.text ?? ""),
  );
  // Place reminder before the user's text so the prompt remains the tail.
  const lastTextPartIndex = filteredParts.findLastIndex(
    (part) => part.type === "text",
  );
  const insertIndex = lastTextPartIndex >= 0 ? lastTextPartIndex : 0;

  messageToInject.parts = [
    ...filteredParts.slice(0, insertIndex),
    reminderPart,
    ...filteredParts.slice(insertIndex),
  ];
  return messages;
}

/** Back-compat wrapper composing static + dynamic memory prompts. */
export function buildAutoMemoryPrompt(
  context: AutoMemoryContext | undefined,
): string {
  const staticPart = buildAutoMemoryStaticPrompt(context);
  const dynamicPart = buildAutoMemoryDynamicPrompt(context);
  if (!staticPart && !dynamicPart) return "";
  if (!dynamicPart) return staticPart;
  if (!staticPart) return dynamicPart;
  return `${staticPart}\n\n${dynamicPart}`;
}

export function buildAutoMemoryExtractionDirective({
  context,
  previousMessageCount,
  maxSteps,
}: {
  context: AutoMemoryContext;
  previousMessageCount: number;
  /** Assistant-turn budget for this run; exceeding it fails the run. */
  maxSteps: number;
}): string {
  return `Extract durable long-term memories from the parent conversation.

Memory directory: ${context.memoryDir}

Review the conversation after message index ${previousMessageCount}. Save only stable information that should help in future sessions. Ignore one-off task progress, transient errors, git history, command output, and information already present in project rules.

Step budget: ${maxSteps} assistant turns. Every turn counts, whether it calls a tool or not, and the run fails with partial work if the budget is exhausted. Multiple tool calls emitted in the same turn cost a single turn, so plan for:
- new topic: writeToFile, then attemptCompletion (2 turns);
- existing topic: readFile, one applyDiff, then attemptCompletion (3 turns);
- nothing durable: attemptCompletion only (1 turn).

Available tools — only these are permitted, and calling anything else wastes a turn:
- readFile: read one existing topic file under the memory directory, or MEMORY.md if the manifest is truncated.
- writeToFile: create a new topic file.
- applyDiff: change part of an existing topic file.
- attemptCompletion: end the run.

Do not explore. Use the topic manifest below and the parent conversation already in your context. If the manifest says entries were omitted, you may spend one turn reading MEMORY.md for the complete index before choosing a topic.

Existing topic manifest:
${formatAutoMemoryManifest(context.manifest)}

Required behavior:
- Save at most ONE topic per run. If several things look durable, record the most important one and leave the rest for a later run.
- Emit every file write for that topic in a SINGLE turn as parallel tool calls; never spread writes across turns.
- Do NOT call attemptCompletion in the same turn as a file write: it is dropped when a turn also calls another tool, wasting the turn. Always leave attemptCompletion its own turn.
- Prefer a brand new topic file over editing an existing one when the subject is new: writeToFile needs no prior readFile.
- When updating an existing topic, make exactly one applyDiff at one site. Do not rewrite the whole file.
- Use markdown topic files directly in the memory directory only; do not use subdirectories.
- Every topic file must start with YAML frontmatter:
---
name: Short stable name
description: One sentence summary
type: user | feedback | project | reference
---
- Do NOT create or edit MEMORY.md. The index is generated from the frontmatter above, so accurate name/description fields are what makes a memory discoverable.
- If there is nothing durable to save, do not modify files.
- Finish with attemptCompletion summarizing whether memory changed. If you are on your last turn, call attemptCompletion immediately so the work already written is recorded.`;
}

export type AutoMemoryDreamSession = {
  taskId: string;
  updatedAt: number;
  cwd?: string | null;
  /**
   * Transcript filename relative to {@link AutoMemoryContext.transcriptDir}.
   * The dream agent reads transcripts on demand via the readFile tool — no
   * transcript content is shipped inline in the directive.
   */
  transcriptFilename: string;
  title?: string;
};

export function buildAutoMemoryDreamDirective({
  context,
  sessions,
}: {
  context: AutoMemoryContext;
  sessions: readonly AutoMemoryDreamSession[];
}): string {
  const sessionText =
    sessions.length === 0
      ? "No sessions were available."
      : sessions
          .map((session) => {
            const titlePart = session.title ? `, title="${session.title}"` : "";
            return `- ${session.transcriptFilename} (taskId=${session.taskId}, updated=${new Date(
              session.updatedAt,
            ).toISOString()}, cwd=${session.cwd ?? "(unknown)"}${titlePart})`;
          })
          .join("\n");

  return `Consolidate long-term memory for this repository.

Memory directory: ${context.memoryDir}
Transcripts directory: ${context.transcriptDir}

Existing topic manifest:
${formatAutoMemoryManifest(context.manifest)}

Source material lives as markdown files in the transcripts directory above. Each file is one task session and starts with a YAML frontmatter block (taskId, cwd, updatedAt, title). The transcripts directory is read-only for this run — use readFile / listFiles / globFiles / searchFiles to inspect only the entries you need, and never edit them.

Strategy:
- Use the preceding parent conversation as source material already in context. Select other sessions by their titles and relevance to durable memory; reviewing every transcript is unnecessary.
- Prefer direct user evidence over large assistant/tool logs. To locate user turns cheaply, search a selected transcript with searchFiles (filePattern set to its filename) for the header pattern "^### [0-9]+[.] user$", then use the returned line numbers with readFile offset/limit to read small ranges around relevant turns. Expand into surrounding messages only when needed to interpret the user's intent or check later corrections.
- Scope content searches to relevant files and specific topics. Search results contain matching lines, so a precise regex can still return a large JSON line. Narrow the files or select message headers if results are truncated.
- If a read is truncated, narrow its range using message boundaries. A single serialized message line can exceed the read limit; line offsets cannot reach the unseen remainder of that same line. Do not repeatedly request its prefix. Seek corroborating user turns or another session, and report any evidence gap that prevents a justified memory change. Do not infer missing content.
- Stop gathering evidence when it is sufficient to decide a memory change or that no durable change is needed; exhaustive transcript reading and reconstruction of large tool outputs are unnecessary.
- Update memory only when a stable user preference, feedback pattern, project fact, or reusable reference emerges. Merge, prune, and rewrite topic files as needed so future sessions see a concise and accurate set of topics.
- Never create or edit MEMORY.md: the index is generated from each topic file's frontmatter. Keep every topic file's name/description accurate instead.
- Keep topic files directly in the memory directory; do not use subdirectories.
- Anchor every entry to direct user intent (explicit instructions, preferences, or feedback) — never promote assistant reasoning, plans, or speculation. When new user feedback contradicts an existing entry and you lack a confident read on the current state, proactively delete it rather than keep outdated guidance.
- Never store ephemeral task status, raw logs, git history, temporary plans, or content already captured by project rules.

Sessions to review (${sessions.length}):
${sessionText}

Finish with attemptCompletion summarizing changed memory files, or state that no durable changes were needed.`;
}

export function serializeMemoryMessage(message: UIMessage): string {
  return JSON.stringify(message, (_key, value) => {
    if (value instanceof Uint8Array) {
      return `[binary ${value.byteLength} bytes]`;
    }
    if (
      value &&
      typeof value === "object" &&
      "url" in value &&
      typeof value.url === "string" &&
      value.url.startsWith("data:")
    ) {
      return { ...value, url: "[data url omitted]" };
    }
    return value;
  });
}
